const fs = require('fs');
let s = fs.readFileSync('app.js','utf8');
function maybe(a,b){const i=s.indexOf(a);if(i>=0)s=s.slice(0,i)+b+s.slice(i+a.length);}
maybe("  const VERSION = 'V1.1.3';","  const VERSION = 'V1.1.4';");
maybe("    uploadConfig: { enabled: false, maxMb: 20, maxFilesPerBatch: 5, maxFilesPerSubmission: 20, allowedExtensions: [] },","    uploadConfig: { enabled: false, maxMb: 20, maxFilesPerBatch: 10, maxFilesPerSubmission: 20, allowedExtensions: [] },");
maybe(`      if (isDriveUrl(pdfUrl) && googleFileId(pdfUrl)) {\n        host.classList.add('pdf-drive-shell');\n        host.innerHTML = \`<iframe class="pdf-drive-frame" src="\${escapeHtml(drivePreviewUrl(pdfUrl))}" title="PDF 教材" loading="lazy" referrerpolicy="no-referrer"></iframe>\`;\n        return;\n      }\n      let data = state.pdfCache.get(contentId);`,`      // V1.1.4: 所有 PDF 都走自有 PDF.js 閱讀器，不再嵌入 Google Drive 預覽器。\n      host.classList.remove('pdf-drive-shell');\n      let data = state.pdfCache.get(contentId);`);
const oldUpload=`  async function uploadSubmissionFiles(lesson, button) {\n    const files = [...state.selectedSubmissionFiles];\n    if (!files.length) return;\n    button.disabled = true;\n    try {\n      for (let i = 0; i < files.length; i++) {\n        const file = files[i];\n        button.textContent = \`上傳中 \${i + 1}/\${files.length}…\`;\n        const fileBase64Value = await fileBase64(file);\n        state.activeSubmission = cacheStudentSubmission(lesson.id, await api('uploadSubmissionFile', { lessonId: lesson.id, fileName: file.name, mimeType: file.type || 'application/octet-stream', fileBase64: fileBase64Value }, state.token, { timeout: 60000 }));\n      }\n      state.selectedSubmissionFiles = [];\n      renderStudentSubmission();\n      showToast('檔案已上傳');\n    } catch (error) { button.disabled = false; button.textContent = '重新上傳'; showToast(error.message || '上傳失敗'); }\n  }`;
const newUpload=`  async function uploadSubmissionFiles(lesson, button) {\n    const files = [...state.selectedSubmissionFiles];\n    if (!files.length) return;\n    button.disabled = true;\n    try {\n      const totalBytes = files.reduce((sum, file) => sum + n(file.size), 0);\n      const canBatch = !!state.features.batchUploadV114 && files.length > 1 && totalBytes <= 6 * 1024 * 1024;\n      if (canBatch) {\n        button.textContent = \`整理 \${files.length} 個檔案…\`;\n        const encoded = await Promise.all(files.map(async file => ({\n          fileName: file.name,\n          mimeType: file.type || 'application/octet-stream',\n          fileBase64: await fileBase64(file)\n        })));\n        button.textContent = \`一次上傳 \${files.length} 個檔案…\`;\n        state.activeSubmission = cacheStudentSubmission(lesson.id, await api('uploadSubmissionFilesBatch', { lessonId: lesson.id, files: encoded }, state.token, { timeout: 120000 }));\n      } else {\n        for (let i = 0; i < files.length; i++) {\n          const file = files[i];\n          button.textContent = \`上傳中 \${i + 1}/\${files.length}…\`;\n          const fileBase64Value = await fileBase64(file);\n          state.activeSubmission = cacheStudentSubmission(lesson.id, await api('uploadSubmissionFile', { lessonId: lesson.id, fileName: file.name, mimeType: file.type || 'application/octet-stream', fileBase64: fileBase64Value }, state.token, { timeout: 60000 }));\n        }\n      }\n      state.selectedSubmissionFiles = [];\n      renderStudentSubmission();\n      showToast('檔案已上傳');\n    } catch (error) { button.disabled = false; button.textContent = '重新上傳'; showToast(error.message || '上傳失敗'); }\n  }`;
if(s.includes(oldUpload)) s=s.replace(oldUpload,newUpload);
else if(!s.includes("uploadSubmissionFilesBatch")) throw new Error('missing upload function');
fs.writeFileSync('app.js',s,'utf8');
let h=fs.readFileSync('index.html','utf8');h=h.replace(/V1\.1\.3/g,'V1.1.4').replace(/v=1\.1\.3/g,'v=1.1.4');fs.writeFileSync('index.html',h,'utf8');
console.log('patched V1.1.4 UX + batch compatibility');
